version: "3.8"

services:
  vite-app:
    build:
      context: ./my-app  # Указываем путь к папке с Dockerfile
      dockerfile: Dockerfile  # Имя Dockerfile (по умолчанию)
    ports:
      - "5173:5173"  # Прокидываем порт Vite
    volumes:
      - ./my-app:/app  # Монтируем код внутрь контейнера
      - /app/node_modules  # Исключаем node_modules (чтобы не перезаписывались)
    environment:
      - CHOKIDAR_USEPOLLING=true  # Исправляет hot-reload в Docker
    command: ["npm", "run", "dev", "--", "--host"]