version: "3.8"

services:
  vite-app:
    build: .
    ports:
      - "5173:5173" # Прокидываем порт Vite
    volumes:
      - .:/app # Монтируем код внутрь контейнера
      - /app/node_modules # Исключаем node_modules (чтобы не перезаписывались)
    environment:
      - CHOKIDAR_USEPOLLING=true # Исправляет hot-reload в Docker
    command: ["npm", "run", "dev", "--", "--host"]