name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Деплой при пуше в main

permissions:
  contents: write  # Разрешаем Actions пушить файлы

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Проверяем файлы в репозитории
        run: ls -la  # Выводит список файлов в корне

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t my-vite-app .  # Точка указывает на текущую директорию

      - name: Run container and extract build
        run: |
          docker run --rm -v $PWD/dist:/app/dist my-vite-app

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist  # Папка с готовыми файлами для деплоя